sudo: false
language: python
install:
- pip install tox coveralls coverage
script:
- .travis.script
after_success:
- "COVERAGE_FILE=.coverage coverage combine"
- coveralls
env:
- TOXENV=py27
- TOXENV=py33
- TOXENV=py34
- TOXENV=flake8
