language: python
install:
- pip install tox coveralls
script:
- tox
- coverage report --show-missing
after_success:
- "! [ '$TOXENV' = 'flake8' ] && coveralls -d .coverage.$TOXENV"
env:
- TOXENV=py27
- TOXENV=py33
- TOXENV=py34
- TOXENV=flake8
